#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/vnfap/vnfap /usr/bin/vnfap
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/vnfap.service ]; then
			rm /etc/systemd/system/vnfap.service /usr/lib/systemd/system/vnfap.service /usr/lib/systemd/user/vnfap.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/vnfap/files/systemd/vnfap.service /usr/lib/systemd/system/vnfap.service
		# try fix error in Ubuntu 18.04
		# Failed to reload vnfap.service: Unit vnfap.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/vnfap.service:10: Executable path is not absolute: pkill -f "vnfap --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/vnfap.service
		fi
		systemctl daemon-reload
		systemctl enable vnfap
		systemctl start vnfap
	fi
fi
